### ISSUE TITLE
Length Extension Attack

### ISSUE THREAD

**Issue by kousu** [timbertson/supergenpass#1]
https://github.com/gfxmonk/supergenpass/blob/a0dce90670a9bc0dda1713b935831d9441041e6c/core/supergenpass/sgp.py#L51

```
pass_cand = passwd + ':' + domain
pass_cand = md5.b64_md5(pass_cand)
```

is a classic example of hashing exploitable by [length extension](https://en.wikipedia.org/wiki/Length_extension_attack). To be fair, I can't imagine a way that this would be exploitable _for this use case_, but I think you should be aware that this is hiding in your code, unquestioned.

**Comment by timbertson** [comment]
It may be of more use pointing this out on https://github.com/chriszarate/supergenpass, since this repo is a compatible implementation (the decision of how the plaintext is constructed is theirs, not mine, and I couldn't change this implementation without breaking compatibility).

However: thanks for pointing this out. As far as I can tell, I agree that this shouldn't be an issue in this use case.
- the "existing hash" is itself secret, in that it's a site-specific password (and it's not the full digest state, since we just take the first `n` bytes).
- length extension would allow you to generate a hash that matches `password+domain+ext`, but `domain+ext` would have to be an existing site (you don't get to pick `ext` freely, you would have to pick a `domain` which is a valid prefix of the target domain). `domain` would have to be a valid TLD, _and_ a prefix of the target domain which correctly aligns with the hash algorithm's padding size.

..and if you _did_ manage to do this, supergenpass' subdomain removal ought to screw it up anyway - by default we don't generate passwords for `a.b.com`, we'd clip it to `b.com`.

**Comment by kousu** [comment]
Further, you could only do length-extension if you'd broken into a site and gotten password dumps _and_ reversed the on-site hashing, if any, _and_ guessed what password hasher the user was using.

**Comment by timbertson** [comment]
Right, but if you register the shorter domain (and get the user to sign up or try to log in via phishing), you wouldn't have to hack the shorter site's generated password, it would be handed to you.
